### ISSUE TITLE
vdraw_intensity_step_regular_cpp fails

### ISSUE THREAD

**Issue by yuliia-sereda** [bladder-ca/nhppp#26]
The `vdraw_intensity_step_regular_cpp` version fails and restarts the R session; `vztdraw_sc_step_regular_cpp` works fine.

**Comment by ttrikalin** [comment]
This seems to work fine in the tests 
can you `reload_all(recompile = TRUE)` to force recompiling?  and check?

**Comment by yuliia-sereda** [comment]
Fails after recompiling. I don't see `vdraw_intensity_step_regular_cpp` in tests. There are tests only for special cases: `vdraw_sc_step_regular_cpp.R` and `vztdraw_sc_step_regular_cpp`.

**Comment by ttrikalin** [comment]
OK  -- I am going to go through all vectorized functions and clean up, 
all arguments should be NULL by default 
logic to clean up arguments is in helper functions 
test files examine all functions

**Comment by ttrikalin** [comment]
I just did a push that works on my machine for the `example.R` in `refactor`. it also passes all tests. 

@yuliia-sereda Can you check that it works on yours?

**Comment by yuliia-sereda** [comment]
It doesn't work. R session is terminated during `_cpp` tests (that's after update and recompiling).

**Comment by ttrikalin** [comment]
Amazing TA TrikalinosOn Mar 4, 2024, at 2:35 PM, yuliia-sereda ***@***.***> wrote:﻿
It doesn't work. R session is terminated during _cpp tests (that's after update and recompiling).

**Comment by ttrikalin** [comment]
The current `dev` and `vfuncs` (ver 0.1.3.9000) works fine on my computer. Can you check? 
it has tests to check from `test()`

**Comment by ttrikalin** [comment]
This issue appears to have been resolved
